// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnT3wM1tyLSb8AtAYXFOAxhSM1BQhBXdU',
    appId: '1:222534601104:web:1a875f8e9cb54cb1b6cb15',
    messagingSenderId: '222534601104',
    projectId: 'design-thinking-f9320',
    authDomain: 'design-thinking-f9320.firebaseapp.com',
    storageBucket: 'design-thinking-f9320.firebasestorage.app',
    measurementId: 'G-GXN6EJ4NR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHVGbHlfb8GXXrUsptAm6SSlwIj3jiUvc',
    appId: '1:222534601104:android:d1e1f596253db3d5b6cb15',
    messagingSenderId: '222534601104',
    projectId: 'design-thinking-f9320',
    storageBucket: 'design-thinking-f9320.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACVrOQ-qiITRyN0wKVLj5a5YWMtizQY8g',
    appId: '1:222534601104:ios:c98a99bc6cd06bb2b6cb15',
    messagingSenderId: '222534601104',
    projectId: 'design-thinking-f9320',
    storageBucket: 'design-thinking-f9320.firebasestorage.app',
    iosBundleId: 'com.example.designThinking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACVrOQ-qiITRyN0wKVLj5a5YWMtizQY8g',
    appId: '1:222534601104:ios:c98a99bc6cd06bb2b6cb15',
    messagingSenderId: '222534601104',
    projectId: 'design-thinking-f9320',
    storageBucket: 'design-thinking-f9320.firebasestorage.app',
    iosBundleId: 'com.example.designThinking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnT3wM1tyLSb8AtAYXFOAxhSM1BQhBXdU',
    appId: '1:222534601104:web:99ec6aa28fda4a67b6cb15',
    messagingSenderId: '222534601104',
    projectId: 'design-thinking-f9320',
    authDomain: 'design-thinking-f9320.firebaseapp.com',
    storageBucket: 'design-thinking-f9320.firebasestorage.app',
    measurementId: 'G-BN4VS1N7MW',
  );
}
